config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  get "posts/search", to: "posts#search"
  get "categories/search", to: "categories#search"

  resources :posts, :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :category
  has_many :orders
  has_many :order_details

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  has_many :books
  enum category_type: {
    "Learning" => 0,
    "Entertainment" => 1,
    "Sports" => 2,
  }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :book
  belongs_to :user
  has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :book
  belongs_to :order

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  default_scope -> { where(status: true).order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  enum level: {
    "Standard" => 0,
    "Premium" => 1,
    "VIP" => 2,
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  def record_not_found
    render json: { error: "404 Not Found" }, status: 404
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    categories = Category.all
    render json: categories
  end

  def create
    category = Category.create(category_params)
    if category.persisted?
      render json: category
    end
  end

  def show
    category = Category.find(params[:id])
    render json: category
  end

  def update
    category = Category.find(params[:id])
    category.update(update_params)
    render json: category
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
  end

  private

  def category_params
    params.require(:category).permit(:title, :description, :category_type)
  end

  def update_params
    params.require(:category).permit(:title, :description, :category_type)
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController

  STANDARD = 2
  PREMIUM = 5
  VIP = 10

  def total_price(order)
    details = OrderDetail.where('order_id=' + order.id)
    sum = 0
    details.each { |detail|
      book = Book.first('id=' + detail.book_id.to_s)
      sum += book.price * detail.quantity
    }
    sum
  end

  def price(order)
    user = User.where('id=' + order.user_id)
    if user.level == 0
      discount = STANDARD
    else
      if user.level == 1
        discount = PREMIUM
      else
        discount = VIP
      end
    end
    total_price(order) * (100 - discount) / 100
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    posts = Post.all
    render json: posts
  end

  def create
    post = Post.create(post_params)
    if post.persisted?
      render json: post
    end
  end

  def show
    post = Post.find(params[:id])
    render json: post
  end

  def update
    post = Post.find(params[:id])
    post.update(update_params)
    render json: post
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
  end

  private

  def post_params
    params.require(:post).permit(:category_id, :title, :description, :author)
  end

  def update_params
    params.require(:post).permit(:category_id, :title, :description, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
  <div>
    <%= form.label :title, class: "col-form-label" %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, class: "col-form-label" %><br>
    <%= form.text_area :description, class: "form-control" %><br>
  </div>

  <div>
    <%= form.label :category_type, class: "col-form-label" %><br>
    <%= form.select :category_type, Category.category_types.keys, class: "form-control" %>
  </div>

  <br>
  <div>
    <%= form.submit :Create, class: "btn btn-dark" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<table class="table table-striped">
  <thead class="table-dark">
  <tr>
    <th scope="col">#</th>
    <th scope="col">Title</th>
    <th scope="col">Content</th>
    <th scope="col">Type</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% index = 1 %>
  <% @categories.each do |category| %>
    <tr>
      <th scope="row">
        <%= index %></th>
      <td><%= category.title %></td>
      <td><%= category.description %></td>
      <td><%= category.category_type %></td>
      <td>
        <%= link_to "Show", category, class: 'btn btn-primary mx-2' %>
        <%= link_to "Edit", edit_category_path(category), class: 'btn btn-success mx-2' %>
        <%= link_to "Destroy", category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mx-2' %>
      </td>
    </tr>
    <% index += 1 %>
  <% end %>

  </tbody>
</table>
<%= link_to "New Category", new_category_path, class: 'btn btn-dark' %>
<%= link_to "Posts", posts_path, class: 'btn btn-dark' %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render "form", category: @category %>

app/views/categories/search.html.erb
<h1>Categories</h1>
<div class="row justify-content-md-end">
  <div class="col-3">
    <form action="/categories/search">
      <div class="input-group mb-3 ">
        <input type="text" class="form-control col-xs-3" name="vls" aria-label="Search" aria-describedby="button-addon">
        <button class="btn btn-dark" type="submit" id="button-addon">Search</button>
      </div>
    </form>
  </div>
</div>
<table class="table table-striped">
  <thead class="table-dark">
  <tr>
    <th scope="col">#</th>
    <th scope="col">Title</th>
    <th scope="col">Content</th>
    <th scope="col">Type</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% index = 1 %>
  <% @categories.each do |category| %>
    <tr>
      <th scope="row">
        <%= index %></th>
      <td><%= category.title %></td>
      <td><%= category.description %></td>
      <td><%= category.category_type %></td>
      <td>
        <%= link_to "Show", category, class: 'btn btn-primary mx-2' %>
        <%= link_to "Edit", edit_category_path(category), class: 'btn btn-success mx-2' %>
        <%= link_to "Destroy", category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mx-2' %>
      </td>
    </tr>
    <% index += 1 %>
  <% end %>

  </tbody>
</table>
<%= link_to "New Category", new_category_path, class: 'btn btn-dark' %>
<%= link_to "Posts", posts_path, class: 'btn btn-dark' %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

<h6>Type: <%= @category.category_type %></h6>

<h6>Description:</h6>

<p><%= @category.description %></p>

<ul>
  <li><%= link_to "Edit", edit_category_path(@category), class: "text-decoration-none" %><br></li>
  <li><%= link_to "Back", categories_path, class: "text-decoration-none" %><br></li>
  <li><%= link_to 'Destroy', @category, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-decoration-none" %>
    <br></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="vi">
<head>
  <title>Wikiapp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "application" %>
</head>

<body>
<div class="container">
  <%= yield %>
  <footer class="mt-5">
    <h6>!Music for fun!</h6>
    <%= image_tag "logo-rb.jpg", style: "height:100px;width:100px", alt: "Lucky - Nito-Onna, Mert Can" %>
  </footer>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <div>
    <%= form.label :title, class: "col-form-label" %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= form.label :category, class: "col-form-label" %><br>
    <%= form.select :category_id, Category.all.map { |c| [c.title, c.id] }, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, class: "col-form-label" %><br>
    <%= form.text_area :description, class: "form-control" %><br>
  </div>

  <div>
    <%= form.label :author, class: "col-form-label" %><br>
    <%= form.text_field :author, class: "form-control" %>
  </div>

  <br>
  <div>
    <%= form.submit :Create, class: "btn btn-dark" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<table class="table table-striped">
  <thead class="table-dark">
  <tr>
    <th scope="col">#</th>
    <th scope="col">Title</th>
    <th scope="col">Content</th>
    <th scope="col">Category</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% index = 1 %>
  <% @posts.each do |post| %>
    <tr>
      <th scope="row">
        <%= index %></th>
      <td><%= post.title %></td>
      <td><%= post.description %></td>
      <td><%= post.category.title %></td>
      <td>
        <%= link_to "Show", post, class: 'btn btn-primary mx-2' %>
        <%= link_to "Edit", edit_post_path(post), class: 'btn btn-success mx-2' %>
        <%= link_to "Destroy", post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mx-2' %>
      </td>
    </tr>
    <% index += 1 %>
  <% end %>

  </tbody>
</table>
<%= link_to "New Post", new_post_path, class: 'btn btn-dark' %>
<%= link_to "Categories", categories_path, class: 'btn btn-dark' %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

app/views/posts/search.html.erb
<h1>Posts</h1>
<div class="row justify-content-md-end">
  <div class="col-3">
    <form action="/posts/search">
      <div class="input-group mb-3 ">
        <input type="text" class="form-control col-xs-3" name="vls" aria-label="Search" aria-describedby="button-addon">
        <button class="btn btn-dark" type="submit" id="button-addon">Search</button>
      </div>
    </form>
  </div>
</div>

<table class="table table-striped">
  <thead class="table-dark">
  <tr>
    <th scope="col">#</th>
    <th scope="col">Title</th>
    <th scope="col">Content</th>
    <th scope="col">Category</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% index = 1 %>
  <% @posts.each do |post| %>
    <tr>
      <th scope="row">
        <%= index %></th>
      <td><%= post.title %></td>
      <td><%= post.description %></td>
      <td><%= post.category.title %></td>
      <td>
        <%= link_to "Show", post, class: 'btn btn-primary mx-2' %>
        <%= link_to "Edit", edit_post_path(post), class: 'btn btn-success mx-2' %>
        <%= link_to "Destroy", post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mx-2' %>
      </td>
    </tr>
    <% index += 1 %>
  <% end %>

  </tbody>
</table>
<%= link_to "New Post", new_post_path, class: 'btn btn-dark' %>
<%= link_to "Categories", categories_path, class: 'btn btn-dark' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<h6>Category: <%= @post.category.title %></h6>

<h6>Author: <%= @post.author %></h6>

<h6>Description:</h6>

<p><%= @post.description %></p>

<ul>
  <li><%= link_to "Edit", edit_post_path(@post), class: "text-decoration-none" %><br></li>
  <li><%= link_to "Back", posts_path, class: "text-decoration-none" %><br></li>
  <li><%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-decoration-none" %>
    <br></li>
</ul>